[package]
name = "hypersonic_v1_api_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
ethers = { version = "2.0.10", features = ["legacy"] }
hex = "0.4.3"
dotenv = "0.15.0"

[[bin]]
name = "quote"
path = "1_quote.rs"

[[bin]]
name = "buildtx"
path = "2_build.rs"

[[bin]]
name = "full"
path = "3_full.rs"